[김성태] user'데이터베이스 모델링
wecode-bootcamp-korea/13-Wellie-backend pull request #2
Opened 2020-11-04 07:34 UTC by kimst5418

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-04 07:49 UTC, ulfrid requested changes
수정부탁드립니다.

2020-11-04 07:49 UTC, ulfrid commented on user/models.py
> +    email             = models.CharField(max_length = 50, null =True)
```suggestion
    email             = models.CharField(max_length = 50, null =True, unique=True)
```
유일해야하는 데이터는 로직만이 아니라 모델에서도 검증해주세요.

2020-11-04 08:06 UTC, kimst5418 commented on user/models.py
> +    email             = models.CharField(max_length = 50, null =True)
밀리의 서재 사이트에서 자체서비스에 가입했는지, 소셜로그인 유저인지에 따라서도 유저를 분리하는데 
독특하게도 이메일 과 모바일 번호 중복을 허용하고 있습니다. usertype 을 통해 어떤 방식으로 가입한 계정인지 구분할 예정입니다.
User name은 중복 불가라 unique=True 옵션을 추가하였습니다.

2020-11-04 09:43 UTC, ulfrid commented on user/models.py
> +    email             = models.CharField(max_length = 50, null =True)
네 알겠습니다!

2020-11-04 09:46 UTC, ulfrid requested changes
댓글 확인해주세요!

2020-11-04 09:46 UTC, ulfrid commented on user/models.py
> +    email             = models.CharField(max_length = 50, null =True)
그렇다면 컬럼중에 소셜 아이디는 어디에 저장하죠?

2020-11-04 11:05 UTC, kimst5418 commented on user/models.py
> +    email             = models.CharField(max_length = 50, null =True)
소셜로그인에 대해 아직 이해가 부족하여 가능한지는 모르겠지만 Usertype 테이블에서 번호/카카오/네이버/구글   등으로 나누고 User 테이블에서 usertype을 ForeignKey로가지게 하여 User id를 통해 유저를 구분하려고 하였습니다.

2020-11-05 06:17 UTC, kimst5418 commented on user/models.py
> +    email             = models.CharField(max_length = 50, null =True)
User 테이블에 social_id 추가하였습니다.

2020-11-05 06:32 UTC, ulfrid commented
LGTM

2020-11-05 06:32 UTC, merged