[김성태] 'library' App 모델링
wecode-bootcamp-korea/13-Wellie-backend pull request #4
Opened 2020-11-04 07:44 UTC by kimst5418

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 'library' App models.py 작성
		 
## 수정 사항들 자세한 내용
- library 앱 생성
- 모델링에 맞게 models.py 작성

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-04 09:21 UTC, ulfrid requested changes
확인 바랍니다~🙂

2020-11-04 09:21 UTC, ulfrid commented on library/models.py
> +    read       = models.BooleanField()
```suggestion
    read       = models.BooleanField(default=False)
```
nullable 한게 아니라면, default=False와 같이 기본값을 지정하는게 좋을것 같습니다. 
null 허용한다면 null=True를 써주세요.  
기존에는 NullBooleanField가 존재했으나 3.1에 Deprecated되었습니다.

2020-11-04 11:33 UTC, kimst5418 commented on library/models.py
> +    read       = models.BooleanField()
반영하였습니다.

2020-11-05 08:44 UTC, ulfrid commented
LGTM

2020-11-05 08:44 UTC, merged